import React, { useState } from "react";
import { AttackVisualizationRouter } from "../attack-graphics/AttackVisualizationRouter";
import type { Alert, FlowEvent, Metrics, ThreatClass } from "../../types";

const SCENARIO_ITEMS = [
  { id: "syn_flood", name: "SYN Flood", category: "Volumetric / DoS", desc: "High-frequency TCP SYN packet streams exhausting server connection pools." },
  { id: "port_scanning", name: "Port Scanning", category: "Reconnaissance", desc: "Sequential probe connections across multiple destination port ranges." },
  { id: "dns_tunnelling", name: "DNS Tunnelling", category: "Exfiltration / C2", desc: "High-entropy, base64-encoded subdomains abusing DNS protocol for data exfiltration." },
  { id: "dga", name: "DGA Domain", category: "Malware C2", desc: "Algorithmic pseudo-random domain queries generated by malware implants." },
  { id: "beaconing", name: "Botnet Beaconing", category: "Command & Control", desc: "Periodic, heartbeat outbound connection requests to C2 server IPs." },
  { id: "encrypted_session", name: "Encrypted Anomaly", category: "Protocol Abuse", desc: "Suspicious TLS/QUIC session metadata and abnormal handshake characteristics." },
  { id: "exfiltration", name: "Data Exfiltration", category: "Data Theft", desc: "Unusual outbound byte asymmetry and large file transfer ratios." },
  { id: "udp_amplification", name: "UDP Amplification", category: "DDoS Reflection", desc: "Reflected UDP traffic streams causing bandwidth saturation." },
  { id: "slowloris", name: "Slowloris DoS", category: "Application Layer", desc: "Long-lived partial HTTP connections holding web server worker threads." },
];

// Presentation-only mock alert for visualization demo — NOT connected to backend
const buildMockAlert = (_scenarioId: string): Alert => ({
  alert_id: "demo-alert-landing",
  timestamp: new Date().toISOString(),
  detector: "hybrid_engine",
  model_version: "2.1.0",
  threat_class: "ddos" as ThreatClass,  // presentation display only
  severity: "high",
  confidence: 0.96,
  source_ip: "192.168.1.105",
  destination_ip: "10.0.0.4",
  protocol: "TCP",
  window_seconds: 10,
  flow_id: "flow-demo-001",
  evidence: [
    { feature: "syn_ratio", reason: "SYN ratio exceeds 0.70 threshold", value: 0.94 },
    { feature: "incomplete_handshakes", reason: "High rate of incomplete handshakes", value: 1240 }
  ],
  explanation: null,
  source_mode: "simulation"
});

// Presentation-only mock flows — purely visual, no backend interaction
const MOCK_FLOWS: FlowEvent[] = Array.from({ length: 25 }, (_, i) => ({
  flow_id: `demo-f-${i}`,
  timestamp: new Date().toISOString(),
  source_ip: "192.168.1.105",
  source_port: 40000 + i,
  destination_ip: "10.0.0.4",
  destination_port: 80,
  protocol: "TCP",
  packets: 150,
  bytes: 84000,
  direction: "inbound" as const,
  tcp_flags: ["SYN"],
  connection_completed: false,
  dns_query: "exfil.data.sub.internal.net",
  source_mode: "simulation" as const,
}));

const MOCK_METRICS: Metrics = {
  processed_events: 12500,
  alerts_generated: 1,
  events_per_second: 2400,
  average_alert_latency_ms: 0.85,
  scenario: "syn_flood",
  status: "completed",
  running: false,
  started_at: null,
  finished_at: null,
  threat_counts: { syn_flood: 1 },
  error_count: 0,
};

export const LandingThreatShowcase: React.FC = () => {
  const [selectedId, setSelectedId] = useState<string>("syn_flood");
  const activeScenario = SCENARIO_ITEMS.find((s) => s.id === selectedId) || SCENARIO_ITEMS[0];

  return (
    <section className="oz-landing-section" id="scenarios">
      <div className="oz-landing-section-header">
        <span className="oz-landing-section-kicker">THREAT SCENARIO SUITE</span>
        <h2 className="oz-landing-section-heading">Nine distinct threat behaviors.</h2>
        <p className="oz-landing-section-sub">
          Explore ORION-Z's passive detection models across volumetric attacks, C2 beaconing, DNS tunnelling, and stealthy application-layer threats.
        </p>
      </div>

      {/* Scenario Selector Pills */}
      <div className="oz-landing-threat-selector">
        {SCENARIO_ITEMS.map((item) => (
          <button
            key={item.id}
            className={`oz-landing-threat-tab ${selectedId === item.id ? "active" : ""}`}
            onClick={() => setSelectedId(item.id)}
          >
            {item.name}
          </button>
        ))}
      </div>

      {/* Active Threat Visual Container — PRESENTATION ONLY */}
      <div style={{ background: "#0a0f1d", border: "1px solid #1e293b", borderRadius: "24px", padding: "32px", color: "#ffffff" }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "16px", marginBottom: "24px", borderBottom: "1px solid #1e293b", paddingBottom: "20px" }}>
          <div>
            <span style={{ fontSize: "11px", fontFamily: "var(--font-mono)", color: "#38bdf8", fontWeight: 700, letterSpacing: "0.06em", display: "block", marginBottom: "4px" }}>
              CATEGORY: {activeScenario.category.toUpperCase()}
            </span>
            <h3 style={{ fontSize: "24px", fontWeight: 800, margin: 0, color: "#ffffff" }}>{activeScenario.name}</h3>
          </div>
          <div style={{ background: "#0f172a", border: "1px solid #334155", padding: "8px 16px", borderRadius: "9999px", fontSize: "12px", fontFamily: "var(--font-mono)", color: "#10b981", fontWeight: 700 }}>
            ● ISOLATED PRESENTATION MODE
          </div>
        </div>

        <p style={{ fontSize: "14px", color: "#94a3b8", marginBottom: "24px", lineHeight: 1.6 }}>
          {activeScenario.desc}
        </p>

        {/* Adapted SVG Attack Visualizer — presentation step only, no backend replay */}
        <div style={{ minHeight: "360px", background: "#070b14", border: "1px solid #1e293b", borderRadius: "16px", padding: "20px", display: "flex", alignItems: "center", justifyContent: "center" }}>
          <AttackVisualizationRouter
            scenario={selectedId}
            step="enrich"
            latestAlert={buildMockAlert(selectedId)}
            flows={MOCK_FLOWS}
            metrics={MOCK_METRICS}
          />
        </div>
      </div>
    </section>
  );
};
